---
  - hosts: all
    become: yes
    become_method: sudo

    tasks:
    - name: update all packages to the latest version
      apt:
        upgrade: dist
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'